### ISSUE TITLE
Consider replacing dependency "node-slate" with "whiteboard"

### ISSUE THREAD

**Issue by dpilafian** [center-key/gulp-node-slate#1]
**node-slate**
A fork of a dead project that is a node implementation of Slate.
https://github.com/center-key/node-slate

**whiteboard**
A project closing in on a thousand stars that is a node implementation of Slate.
https://github.com/mpociot/whiteboard

...or make **node-slate** a fork of **whiteboard**.

**Comment by dghelm** [comment]
Might consider closing this issue? Seems like `node-slate` outlived everything else :)
